<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Document.Processor" Version="24.2.*"/>
    <PackageReference Include="DevExpress.Drawing.Skia" Version="24.2.*" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Demo.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
