<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Document.Processor"/>
    <PackageReference Include="DevExpress.Drawing.Skia"/>
    <PackageReference Include="Microsoft.CSharp"/>
    <PackageReference Include="System.Data.DataSetExtensions"/>
  </ItemGroup>
  <ItemGroup>
    <None Update="Demo.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
